In [1]:
import numpy as np
import pandas as pd

In [2]:
# Show all column in head()
pd.set_option('display.max_columns', None)

In [3]:
full_df = pd.read_csv('top_8comp_volume_spike_4_POS_NN_manually_labelled.csv')

In [4]:
full_df.head(-1)

,tweetId,isRetweet,hoursDiffFromParent,tweet_userId,followers_count,company_name,afinn_verdict,no_of_positive_words,no_of_negative_words,positive_words,negative_words,Date,Open,High,Low,Close,Adj Close,Volume,volume_vs_5d_avg_vol,5d_gain_percent,5d_loss_percent,20d_gain_percent,20d_loss_percent,cleaned_text_new,NER
0,4.180000e+17,False,0,2.366978e+07,14958,AAPL,NEGATIVE,1,1,big,screwed,12/31/2013 0:00,79.167145,80.182854,79.142860,80.145714,74.571281,55771100,0.824783,0.000000,-3.682317,0.000000,-9.996391,Apple Screwed Up Big Time,Apple
1,4.180000e+17,False,0,2.305950e+07,48081,FB,NEGATIVE,0,1,NaN,warning,12/31/2013 0:00,54.119999,54.860001,53.910000,54.650002,54.650002,43076200,0.655074,6.726208,0.000000,8.111557,-3.821187,Warning Bells Are Sounding Ever Louder For Fac...,FaceBook
2,4.190000e+17,False,0,5.924043e+07,4172,MSFT,NEGATIVE,1,2,responsibility,"anti,hacked",1/2/2014 0:00,37.349998,37.400002,37.099998,37.160000,33.690468,30632200,1.909433,0.000000,-4.097024,0.401061,-6.657674,Following SnapChat Skype twitter and blog hac...,Skype
3,4.200000e+17,True,0,5.185106e+08,250614,AMZN,NEGATIVE,0,1,NaN,killing,1/6/2014 0:00,395.850006,397.000000,388.420013,393.630005,393.630005,3170600,1.465360,2.491188,0.000000,2.785894,-12.440143,Bar Charts Apple vs Amazon vs Google AMZN GOOG...,NaN
4,4.190000e+17,True,-10,2.020527e+07,8415,FB,NEGATIVE,0,1,NaN,lawsuit,1/3/2014 0:00,55.020000,55.650002,54.529999,54.560001,54.560001,38246200,0.707881,5.947883,-0.880249,13.872411,-4.914728,Facebook is facing a lawsuit over claims it mi...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3530,7.150000e+17,False,0,7.080000e+17,1287,AAPL,POSITIVE,3,0,"gain,gain,nice",NaN,3/31/2016 0:00,109.720001,109.900002,108.879997,108.989998,105.879097,25888400,0.874377,2.083712,-0.624541,2.265693,-12.123436,Nice day for the team and I We hit AAPL for a...,NaN
3531,7.150000e+17,False,0,2.447968e+09,13804,AAPL,POSITIVE,1,0,big,NaN,3/31/2016 0:00,109.720001,109.900002,108.879997,108.989998,105.879097,25888400,0.874377,2.083712,-0.624541,2.265693,-12.123436,Three Penny Stock Picks More Than QUADRUPLED I...,NaN
3532,7.150000e+17,False,0,3.984396e+09,7096,AAPL,POSITIVE,1,0,gains,NaN,3/31/2016 0:00,109.720001,109.900002,108.879997,108.989998,105.879097,25888400,0.874377,2.083712,-0.624541,2.265693,-12.123436,Premium Alerts Ranked For Gains Last Week At ...,NaN
3533,7.160000e+17,False,0,9.505171e+08,1760,AAPL,POSITIVE,1,0,shares,NaN,3/31/2016 0:00,109.720001,109.900002,108.879997,108.989998,105.879097,25888400,0.874377,2.083712,-0.624541,2.265693,-12.123436,Apple Still into Uptrend Channel since Februar...,NaN
3534,7.160000e+17,False,0,4.811164e+09,3448,AAPL,POSITIVE,1,0,best,NaN,3/31/2016 0:00,109.720001,109.900002,108.879997,108.989998,105.879097,25888400,0.874377,2.083712,-0.624541,2.265693,-12.123436,REVIEW This is Apple best iPad AAPL,NaN

In [5]:
full_df = full_df.rename(columns={'afinn_verdict': 'target'})

In [6]:
full_df = full_df[['target','cleaned_text_new']]

In [7]:
full_df.head(-1)

        target                                   cleaned_text_new
0     NEGATIVE                          Apple Screwed Up Big Time
1     NEGATIVE  Warning Bells Are Sounding Ever Louder For Fac...
2     NEGATIVE  Following SnapChat  Skype twitter and blog hac...
3     NEGATIVE  Bar Charts Apple vs Amazon vs Google AMZN GOOG...
4     NEGATIVE  Facebook is facing a lawsuit over claims it mi...
...        ...                                                ...
3530  POSITIVE  Nice day for the team and I  We hit AAPL for a...
3531  POSITIVE  Three Penny Stock Picks More Than QUADRUPLED I...
3532  POSITIVE  Premium Alerts Ranked For Gains  Last Week At ...
3533  POSITIVE  Apple Still into Uptrend Channel since Februar...
3534  POSITIVE                REVIEW This is Apple best iPad AAPL

[3535 rows x 2 columns]

In [8]:
full_df['target'] = full_df['target'].map({'POSITIVE':1, 'NEGATIVE':0})

In [9]:
full_df.head(-1)

      target                                   cleaned_text_new
0          0                          Apple Screwed Up Big Time
1          0  Warning Bells Are Sounding Ever Louder For Fac...
2          0  Following SnapChat  Skype twitter and blog hac...
3          0  Bar Charts Apple vs Amazon vs Google AMZN GOOG...
4          0  Facebook is facing a lawsuit over claims it mi...
...      ...                                                ...
3530       1  Nice day for the team and I  We hit AAPL for a...
3531       1  Three Penny Stock Picks More Than QUADRUPLED I...
3532       1  Premium Alerts Ranked For Gains  Last Week At ...
3533       1  Apple Still into Uptrend Channel since Februar...
3534       1                REVIEW This is Apple best iPad AAPL

[3535 rows x 2 columns]

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
%matplotlib inline

Using TensorFlow backend.
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/kooud/anaconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [11]:
X = full_df['cleaned_text_new']
y = full_df['target']

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [45]:
max_words = 200
max_len = 150
tok = Tokenizer(num_words=max_words)
tok.fit_on_texts(X_train)
sequences = tok.texts_to_sequences(X_train)
sequences_matrix = sequence.pad_sequences(sequences,maxlen=max_len)

In [46]:
def RNN():
    inputs = Input(name='inputs',shape=[max_len])
    layer = Embedding(max_words,50,input_length=max_len)(inputs)
    layer = LSTM(64)(layer)
    layer = Dense(256,name='FC1')(layer)
    layer = Activation('relu')(layer)
    layer = Dropout(0.5)(layer)
    layer = Dense(1,name='out_layer')(layer)
    layer = Activation('sigmoid')(layer)
    model = Model(inputs=inputs,outputs=layer)
    return model

In [47]:
model = RNN()
model.summary()
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
inputs (InputLayer)          (None, 150)               0
_________________________________________________________________
embedding_5 (Embedding)      (None, 150, 50)           10000
_________________________________________________________________
lstm_5 (LSTM)                (None, 64)                29440
_________________________________________________________________
FC1 (Dense)                  (None, 256)               16640
_________________________________________________________________
activation_9 (Activation)    (None, 256)               0
_________________________________________________________________
dropout_5 (Dropout)          (None, 256)               0
_________________________________________________________________
out_layer (Dense)            (None, 1)                 257
_________________________________________________________________
activation_10 (Activation)   (None, 1)                 0
=================================================================
Total params: 56,337
Trainable params: 56,337
Non-trainable params: 0
_________________________________________________________________

In [52]:
model.fit(sequences_matrix,y_train,batch_size=64,epochs=10,
          validation_split=0.2,callbacks=[EarlyStopping(monitor='val_loss',min_delta=0.0001)])

Train on 2262 samples, validate on 566 samples
Epoch 1/10
2262/2262 [==============================] - 4s 2ms/step - loss: 0.4351 - accuracy: 0.7745 - val_loss: 0.4848 - val_accuracy: 0.7438
Epoch 2/10
2262/2262 [==============================] - 4s 2ms/step - loss: 0.4116 - accuracy: 0.7922 - val_loss: 0.4777 - val_accuracy: 0.7403
Epoch 3/10
2262/2262 [==============================] - 4s 2ms/step - loss: 0.3990 - accuracy: 0.8002 - val_loss: 0.4934 - val_accuracy: 0.7420

In [53]:
test_sequences = tok.texts_to_sequences(X_test)
test_sequences_matrix = sequence.pad_sequences(test_sequences,maxlen=max_len)

In [54]:
accr = model.evaluate(test_sequences_matrix,y_test)

708/708 [==============================] - 1s 1ms/step

In [55]:
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))

Test set
  Loss: 0.426
  Accuracy: 0.768